name: Deploy web app

on: workflow_dispatch

jobs:
  deploy:

    runs-on: self-hosted
    strategy:
      matrix:
        path: [ "restaurante2-carta.llevoxti.com" ]
    steps:
      - uses: actions/checkout@v3

        #- name: Configure ssh
        #env:
          #SSH_AUTH_SOCK: /tmp/ssh_agent.sock
            #run: |
          #mkdir -p ~/.ssh
          #chmod 700 ~/.ssh
          #ssh-keyscan "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          #chmod 644 ~/.ssh/known_hosts
          #ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          #ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: deploy web app
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: rsync -rz app/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/${{ matrix.path }}
